spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mustnot/numble-k8s-monitoring-system
    targetRevision: HEAD

apps:
  - name: argocd
    namespace: argocd
  - name: nginx
    namespace: default
  - name: eck-operator
    namespace: elastic
  - name: eck-elasticsearch
    namespace: elastic
  - name: eck-kibana
    namespace: elastic
  - name: eck-beats
    namespace: elastic
