apiVersion: v1
kind: Service
metadata:
  name: eck-kibana
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-layer-type: 'nplb'
spec:
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
  selector:
    app: eck-kibana
  type: LoadBalancer
